name: 1-3

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0,6,12,18 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # --- akun-1 ---
          - path: 'akun-1/akun-1b'
          - path: 'akun-1/akun-1_2'
          - path: 'akun-1/akun-1_3'
          - path: 'akun-1/akun-1_4'
          - path: 'akun-1/akun-1_5'
          - path: 'akun-1/akun-1_6'

          # --- akun-2 ---
          - path: 'akun-2/akun-2b'
          - path: 'akun-2/akun-2b_2'
          - path: 'akun-2/akun-2b_3'
          - path: 'akun-2/akun-2b_4'
          - path: 'akun-2/akun-2b_5'
          - path: 'akun-2/akun-2b_6'

          # --- akun-3 ---
          - path: 'akun-3/akun-3'
          - path: 'akun-3/akun-3_2'
          - path: 'akun-3/akun-3_3'
          - path: 'akun-3/akun-3_4'
          - path: 'akun-3/akun-3_5'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget google-chrome-stable

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib selenium requests selenium-stealth undetected-chromedriver

    - name: Download & Extract Files from Google Drive
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FILE_ID }}
      run: python download_drive.py

    - name: Run Bot Script
      run: |
        cd ${{ matrix.path }}
        python3 seofast_zhp.py
